### PR TITLE
Added a single producer single consumer ringbuffer (spsc_ringbuffer.p…

### PR DESCRIPTION
**Pull request by dioannidis**
…as) with an example ringbuffer_test.

### CODE REVIEW

**Comment by ccrause** [comment]
Would you mind adding a short description for this example to the README in the root folder?

**Comment by dioannidis** [comment]
> Would you mind adding a short description for this example to the README in the root folder?

Not at all. I missed that ;)

**Comment by dioannidis** [comment]
BTW, do you know some other way ( instead of using macros that is ), more elegant, to initialize constant static arrays ? 

I'm sure you noticed the defines ....

**Comment by ccrause** [comment]
I don't know of a more compact way in general to initialize an array.  In this example _where all elements are initialized to 0_, it is sufficient to declare the array as a global variable. As a global variable the memory would be zeroed automatically by the RTL startup code, while the explicitly initialized array will store its initial values as data, which then needs to be copied from flash to RAM on startup.

**Comment by dioannidis** [comment]
> Would you mind adding a short description for this example to the README in the root folder?

Done !  See PR https://github.com/ccrause/fpc-avr/pull/3

**Pull request merged**
